---
- name: Install Hyprland dependencies
  pacman:
    name:
      - ninja
      - gcc
      - cmake
      - meson
      - libxcb
      - xcb-proto
      - xcb-util
      - xcb-util-keysyms
      - libxfixes
      - libx11
      - libxcomposite
      - libxrender
      - libxcursor
      - pixman
      - wayland-protocols
      - cairo
      - pango
      - libxkbcommon
      - xcb-util-wm
      - xorg-xwayland
      - libinput
      - libliftoff
      - libdisplay-info
      - cpio
      - tomlplusplus
      - hyprland-git
      - hyprcursor-git
      - hyprwayland-scanner-git
      - xcb-util-errors
      - hypruilts-git
      - glaze
      - hyprgraphics-git
      - aquamarine-git
      - re2
      - hyprland-qtuilts
    state: present

- name: Install Hyprland
  shell: |
    git clone --recursive https://github.com/hyprwm/Hyprland /tmp/Hyprland
    cd /tmp/Hyprland
    make all && make install
  args:
    creates: /usr/bin/Hyprland

- name: Install Arch-Hyprland with Nvidia support
  hosts: localhost
  become: yes
  tasks:
    - name: Clone Arch-Hyprland repository
      ansible.builtin.command:
        cmd: git clone --depth=1 https://github.com/JaKooLit/Arch-Hyprland.git ~/Arch-Hyprland
        creates: ~/Arch-Hyprland  # Skip if directory already exists

    - name: Enable Nvidia and Nouveau in preset.sh
      ansible.builtin.replace:
        path: ~/Arch-Hyprland/preset.sh
        regexp: '(nvidia=")OFF("|.*nouveau=")OFF(")'
        replace: '\1ON\2\3ON\4'
        backup: yes

    - name: Make install.sh executable
      ansible.builtin.file:
        path: ~/Arch-Hyprland/install.sh
        mode: '0755'

    - name: Run installation script
      ansible.builtin.command:
        chdir: ~/Arch-Hyprland
        cmd: ./install.sh