---
- name: Install Gaming Apps
  pacman:
    name:
      - steam
      - gamescope
      - mangohud
      - lib32-mangohud
    state: present

- name: Install Wine & dependencies
  pacman:
    name:
      - wine-staging
      - giflib
      - lib32-giflib
      - gnutls
      - lib32-gnutls
      - v4l-utils
      - lib32-v4l-utils
      - libpulse
      - lib32-libpulse
      - alsa-plugins
      - lib32-alsa-plugins
      - alsa-lib
      - lib32-alsa-lib
      - sqlite
      - lib32-sqlite
      - libxcomposite
      - lib32-libxcomposite
      - ocl-icd
      - lib32-ocl-icd
      - libva
      - lib32-libva
      - gtk3
      - lib32-gtk3
      - gst-plugins-base-libs
      - lib32-gst-plugins-base-libs
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - sdl2-compat
      - lib32-sdl2-compat
    state: present

- name: Install GameMode & Dependencies
  pacman:
    name:
      - gamemode    
      - meson
      - systemd
      - git
      - dbus
      - libinih    
      - lib32-gamemode
    state: present

- name: Add user to gamemode group
  user:
    name: mahatmus
    groups: gamemode
    append: yes

- name: Configure gamemode
  copy:
    dest: /etc/gamemode.ini
    content: |
      [general]
      ; Enable gamemode for all games by default
      defaultgamemode=1
      ; Enable verbose logging for troubleshooting
      verbose=1

      [cpu]
      governor=performance
      core_usage=90
      ; Enable Ryzen-specific optimizations
      enable_amd_pstate=1
      amd_prefcore=1

      [gpu]
      gpu_optimisations=1
      nv_powermizer_mode=1
      ; Wayland/Vulkan focus
      nv_threaded_optimizations=1
      nv_opengl_threaded_optimizations=1

      [memory]
      realtime_priority=80
      vm_watermark_scale=1
      vm_stat_interval=10
      ; improve memory allocation behavior for some games.  
      malloc_madvise=1

      [supervisor]
      ; Wayland/Vulkan focus
      ioprio=0
      renice=-15

      [custom]
      ; Nvidia-specific environment variables
      env_0=__GL_MaxFramesAllowed=1                            ; Limita o número de frames enfileirados pela GPU, reduzindo input lag
      env_1=__GL_SYNC_TO_VBLANK=0                              ; Desativa V-Sync via driver NVIDIA para reduzir latência e stutter
      env_2=WLR_NO_HARDWARE_CURSORS=1                          ; Corrige problemas visuais com o cursor em Wayland/NVIDIA (Hyprland)
      env_3=DXVK_ASYNC=1                                       ; Ativa shaders assíncronos no DXVK, eliminando stutter em troca de possíveis glitches visuais
      env_4=DXVK_STATE_CACHE=1                                 ; Ativa cache de estado no DXVK, evitando recompilação de shaders entre execuções
      env_5=VKD3D_CONFIG=dxr,gpu_feedback                      ; Ativa ray tracing (DXR) e feedback de GPU no vkd3d-proton (para jogos DirectX 12)
      env_6=__GLX_VENDOR_LIBRARY_NAME=nvidia                   ; Garante que o GLX use a biblioteca da NVIDIA corretamente sob Wayland
      env_7=GL_SHADER_DISK_CACHE_PATH=$HOME/.nv-shader-cache   ; Define um diretório persistente para armazenar o cache de shaders da NVIDIA
      env_8=__GL_SHADER_DISK_CACHE=1                           ; Ativa o uso de cache de shaders em disco pela NVIDIA (acelera carregamento)
      env_9=__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1              ; Evita que o driver limpe o cache de shaders automaticamente

      ; Wayland/NVIDIA-Specific Tweaks (Use if Needed)
      ; env_11=WLR_DRM_NO_ATOMIC=1                             ; Helps avoid glitches on NVIDIA under Wayland
      ; env_12=WLR_RENDERER_ALLOW_SOFTWARE=0                   ; Prevents fallback to software rendering

      [script]
      start=notify-send "GameMode Started" "Performance mode activated"
      end=notify-send "GameMode Ended" "Returning to normal mode"
    mode: '0644'

- name: Create the shaders cache directory(NVIDIA)
  ansible.builtin.file:
    path: "/home/mahatmus/.nv-shader-cache"
    state: directory
    mode: '0755'

- name: Install blstrobe for BENQ monitor
  shell: |
    git clone https://github.com/fhunleth/blstrobe.git /tmp/blstrobe
    cd /tmp/blstrobe
    ./autogen.sh && ./configure && make && make install
  args:
    creates: /usr/local/bin/blstrobe