# Created by: mahatmus
title   Arch Linux TKG Bore (linux)
linux   /vmlinuz-linux614-tkg-bore
initrd  /initramfs-linux614-tkg-bore-fallback.img
options root=PARTUUID=ccaa0080-a31c-4873-9c1f-fb7f54ab5c78 rw rootfstype=ext4
