---
- name: Install Nvidia packages
  become: yes
  pacman:
    name:
      - nvidia-dkms
      - nvidia-utils
      - nvidia-settings
      - lib32-nvidia-utils
      - libva-nvidia-driver
      - egl-wayland
      - vulkan-icd-loader
      - vulkan-tools
      - libglvnd
      - opencl-nvidia
    state: present
    extra_args: "--noconfirm"
    update_cache: yes      

#- name: Configure mkinitcpio
#  lineinfile:
#    path: /etc/mkinitcpio.conf
#    regexp: '^MODULES='
#    line: 'MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)'

#- name: Create nvidia.conf
#  copy:
#    dest: /etc/modprobe.d/nvidia.conf
#    content: |
#      options nvidia_drm modeset=1 fbdev=1
#      options nvidia NVreg_RegistryDwords="PowerMizerEnable=0x1; PerfLevelSrc=0x2222; #PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"

#- name: Rebuild initramfs
#  shell: mkinitcpio -P