---
- name: Install Essential Packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
      - git
      - base-devel
      - curl
      - python
      - ansible
      - flatpak
      - amd-ucode

- name: Install YAY from AUR
  become: yes
  shell: |
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    sudo -u nobody makepkg -si --noconfirm
    rm -rf /tmp/yay
  args:
    creates: /usr/bin/yay

- name: Install Firmware
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - linux-headers
    - linux-firmware
    - linux-firmware-qlogic    

- name: Install Firmware via YAY
  become: yes
  become_user: mahatmus
  command: yay -S --noconfirm mkinitcpio-firmware ast-firmware
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Install Firmware via Github
  shell: |
    git clone https://github.com/mahatmus-tech/uPD72020x-Firmware.git /usr/local/uPD72020x-Firmware
    cd /usr/local/uPD72020x-Firmware
    makepkg -si --noconfirm
  args:
    executable: /bin/bash

- name: Install Terminal and Utilities
  become: yes
  pacman:
    name:
      - kitty
      - man-db
      - wget
      - htop
      - nvtop
      - fastfetch
      - pokemon-colorscripts
    state: present
    extra_args: "--noconfirm --needed"
    update_cache: yes      

- name: Install Codecs and Libraries
  become: yes
  pacman:
    name:
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - ffmpeg
      - gstreamer
      - libva
      - libvdpau
      - lame
      - flac
      - wavpack
      - opus
      - faac
      - faad2
      - x264
      - x265
      - libvpx
      - dav1d
      - aom
      - libmpeg2
      - libmad
    state: present
    extra_args: "--noconfirm --needed"
    update_cache: yes

- name: Install Codecs and Libraries via YAY
  become: yes
  shell: yay -S --noconfirm ffmpeg-full
  args:
    executable: /usr/local/yay  

- name: Install Compression Tools
  become: yes
  pacman:
    name:
      - zip
      - unzip
      - p7zip
      - gzip
      - bzip2
      - xz
      - tar
      - rar
      - unrar
      - lrzip
      - zstd
      - lzip
      - lzop
      - arj
      - cabextract
      - cpio
      - unace
    state: present
    extra_args: "--noconfirm --needed"
    update_cache: yes

- name: Install Wayland
  become: yes
  pacman:
    name:
      - waybar
      - wayland    
      - qt5-wayland
      - qt6-wayland
      - qt5ct
      - qt6ct
      - wayland-protocols
      - wlr-randr
    state: present
    extra_args: "--noconfirm --needed"
    update_cache: yes      