---
- name: Install essential packages
  become: yes
  pacman:
    name:
      - git
      - base-devel
      - curl
      - python
      - ansible
      - flatpak
      - amd-ucode
    state: present
    extra_args: "--noconfirm"
    update_cache: yes

- name: Install yay from AUR
  become: yes
  become_user: nobody  # Build as unprivileged user for security
  shell: |
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si --noconfirm --needed
    cd ..
    rm -rf /tmp/yay
  args:
    creates: /usr/bin/yay
  environment:
    HOME: /tmp  # Needed for makepkg to work as nobody

- name: Install firmware
  become: yes
  pacman:
    name:
      - linux-headers
      - linux-firmware
      - linux-firmware-qlogic
    state: present
    extra_args: "--noconfirm"
    update_cache: yes    

- name: Install firmware(yay)
  shell: yay -S --noconfirm ast-firmware mkinitcpio-firmware
  args:
    executable: /bin/bash

- name: Install firmware(git clone)
  shell: |
    git clone https://github.com/mahatmus-tech/uPD72020x-Firmware.git /tmp/uPD72020x-Firmware
    cd /tmp/uPD72020x-Firmware
    makepkg -si --noconfirm
  args:
    creates: /usr/local/bin/uPD72020x-Firmware

- name: Install terminal and utilities
  become: yes
  pacman:
    name:
      - kitty
      - man-db
      - wget
      - htop
      - nvtop
      - fastfetch
      - pokemon-colorscripts
    state: present
    extra_args: "--noconfirm"
    update_cache: yes      

- name: Install codecs and libraries
  become: yes
  pacman:
    name:
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - ffmpeg
      - gstreamer
      - libva
      - libvdpau
      - lame
      - flac
      - wavpack
      - opus
      - faac
      - faad2
      - x264
      - x265
      - libvpx
      - dav1d
      - aom
      - libmpeg2
      - libmad
    state: present
    extra_args: "--noconfirm"
    update_cache: yes    

- name: Install codecs and libraries(yay)
  shell: yay -S --noconfirm ffmpeg-full
  args:
    executable: /bin/bash

- name: Install compression tools
  become: yes
  pacman:
    name:
      - zip
      - unzip
      - p7zip
      - gzip
      - bzip2
      - xz
      - tar
      - rar
      - unrar
      - lrzip
      - zstd
      - lzip
      - lzop
      - arj
      - cabextract
      - cpio
      - unace
    state: present
    extra_args: "--noconfirm"
    update_cache: yes    

- name: Wayland
  become: yes
  pacman:
    name:
      - waybar
      - wayland    
      - qt5-wayland
      - qt6-wayland
      - qt5ct
      - qt6ct
      - wayland-protocols
      - wlr-randr
    state: present
    extra_args: "--noconfirm"
    update_cache: yes      