---
- name: Install Essential Packages
  become: yes
  community.general.pacman:
    name:
      - git
      - base-devel
      - curl
      - python
      - ansible
      - flatpak
      - amd-ucode    
    state: latest

- name: Install Firmware
  become: yes
  community.general.pacman:
    name:
      - linux-headers
      - linux-firmware
      - linux-firmware-qlogic
    state: latest

- name: Install Firmware via YAY
  aur_packages:
    - mkinitcpio-firmware
    - ast-firmware

- name: Install Firmware via Github
  shell: |
    git clone https://github.com/mahatmus-tech/uPD72020x-Firmware.git /tmp/uPD72020x-Firmware
    cd /tmp/uPD72020x-Firmware
    makepkg -si --noconfirm
  args:
    executable: /bin/bash

- name: Install Terminal and Utilities
  become: yes
  community.general.pacman:
    name:
      - kitty
      - man-db
      - wget
      - htop
      - nvtop
      - fastfetch
      - pokemon-colorscripts
    state: latest

- name: Install Codecs and Libraries
  become: yes
  community.general.pacman:
    name:
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - ffmpeg
      - gstreamer
      - libva
      - libvdpau
      - lame
      - flac
      - wavpack
      - opus
      - faac
      - faad2
      - x264
      - x265
      - libvpx
      - dav1d
      - aom
      - libmpeg2
      - libmad
    state: latest

- name: Install Codecs and Libraries via YAY
  aur_packages:
    - ffmpeg-full

- name: Install Compression Tools
  become: yes
  community.general.pacman:
    name:
      - zip
      - unzip
      - p7zip
      - gzip
      - bzip2
      - xz
      - tar
      - rar
      - unrar
      - lrzip
      - zstd
      - lzip
      - lzop
      - arj
      - cabextract
      - cpio
      - unace
    state: latest

- name: Install Wayland
  become: yes
  community.general.pacman:
    name:
      - waybar
      - wayland    
      - qt5-wayland
      - qt6-wayland
      - qt5ct
      - qt6ct
      - wayland-protocols
      - wlr-randr
    state: latest

- name: Run the equivalent of "pacman -Sy" as a separate step
  community.general.pacman:
    update_cache: true